global using FluentValidation;
global using FluentValidation.Results;
global using static March.Web.Utils.Extensions;
global using static March.Web.Features.Client.Counter.Counter;
global using static March.Web.Features.Client.Auth.Login;
global using static March.Web.Features.Client.Form.Form;
global using static March.Web.Features.Client.NavMenu.Nav;
global using static March.Web.Features.Client.Form.FormSubmitted;
global using March.Web;
global using March.Web.Utils;
global using March.Web.Features.Client.Counter;
global using March.Web.Features.Client.Auth;
global using March.Web.Features.Client.Home;
global using March.Web.Features.Server.StaticFiles;
global using March.Web.Features.Client.NavMenu;
global using March.Web.Features.Client.HowItWorks;
global using March.Web.Features.Client.Form;
global using March.Web.Features.Server.EndpointFilters;
global using March.Web.Features.Server.Auth;
global using March.Web.Features.Server.Cors;
global using March.Web.Features.Server.Logging;
global using March.Web.Features.Server.Middleware;
global using March.Web.Features.Server.ResponseCompression;
global using March.Web.Features.Client.AdminDashboard;
global using March.Web.Features.Client.Authentication;
global using March.Web.Features.Server.Rendering;
global using March.Web.Features.Server.FeatureFlags;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.ResponseCompression;
global using Microsoft.AspNetCore.Authentication;
global using System.Security.Claims;